server:
  port: 8091

spring:
  security:
    oauth2:
      client:
        registration:
#          facebook:
#            clientId: client id
#            clientSecret: client secret

          google:
            clientId: client id
            clientSecret: client secret
